name: 1.0$(Rev:.r)

# simplified trigger (implied branch)
trigger: none

# equivalents trigger
# trigger:
#  branches:
#    include:
#    - main

parameters:
  - name: "StorageAccountName"
    displayName: "name of the storage account"
    type: string



steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'veesub(e9ef4e47-6053-4aae-970c-8743b74efc02)'
    subscriptionId: 'e9ef4e47-6053-4aae-970c-8743b74efc02'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'mydevops'
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    #csmFile: 'https://github.com/veevellanki/myrepo1/blob/main/Storageaccount.json'
    csmFile: 'Storageaccount.json'
    overrideParameters: -StorageAccountName ${{parameters.StorageAccountName}}
    #csmParametersFile: 'https://github.com/veevellanki/myfirstdevops/blob/mydevops1/StorageAccount.parameters.json'
    deploymentMode: 'Incremental'
    deploymentName: 'mypipelinedeployment234345'
    addSpnToEnvironment: true

