name: 1.0$(Rev:.r)

# simplified trigger (implied branch)
trigger: none

# equivalents trigger
# trigger:
#  branches:
#    include:
#    - main

variables:
  name: rohit

pool:
  vmImage: ubuntu-latest

jobs:

- job: helloworld
  steps:

    - script: echo "Hello,  Welcome $(name)"